### ISSUE TITLE
interpolate.tree path.dist incomplete

### ISSUE THREAD

**Issue by eric-czech** [RGLab/cytoEx#1]
Perhaps this was a partially complete feature that was never meant to be included?

https://github.com/RGLab/cytoEx/blob/05bd73da82cadf58e46ae86ae6b0aa0efa2ed48f/R/interpolate.tree.R#L58

It's breaking cytoEx installs so I thought I'd point it out.

**Comment by gfinak** [comment]
CytoEx is not released or even supported for that matter, just some ideas we were playing around.

**Comment by eric-czech** [comment]
Ah, specifically I was getting [shinyCyto](https://github.com/RGLab/shinyCyto) up and running which does work after applying some elbow grease but did you guys ever use that project much internally?  I was looking for options on how to expose the openCyto tools to some non-programmers in our lab -- any suggestions?

**Comment by mikejiang** [comment]
`cytoEx` should install now. But as Greg said, both packages are experimental and have not been actively maintained. We do have some long term plan of developing the complete web GUI for `openCyto`. But not sure if we will do it through `shiny` framework.

**Comment by eric-czech** [comment]
Ok makes sense, thanks.
